export { AboutPage } from './AboutPage'
export { ContactPage } from './ContactPage'
export { HomePage } from './HomePage'
export { NotFoundPage } from './NotFoundPage'
export { ServicesPage } from './ServicesPage'
